# This workflow will build a Java project with Gradle

name: Java CI with Gradle

# Triggers the workflow on push or pull request events (on every branch)
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: xinova/arangodb-action@v1
      - name: Set up database
        with:
          arangodb version: 'latest'  # See https://hub.docker.com/_/arangodb for available versions
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run WebOCD Tests with Gradle
        run: ./gradlew testWithoutDB