name: Java CI with Gradle

on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      arangodb:
        image: arangodb/arangodb:3.10.0  
        ports:
          - 8529:8529  # Default ArangoDB port
        options: --health-cmd="curl --fail http://localhost:8529/_api/version || exit 1" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build WebOCD Service
        run: ./gradlew build
        env:
          ARANGO_HOST: localhost
          ARANGO_PORT: 8529

