name: Java CI with Gradle

on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      arangodb:
        image: arangodb/arangodb:3.10.0
        ports:
          - 8529:8529  # Default ArangoDB port
        env:
          ARANGO_ROOT_PASSWORD: password  # Set the root password as expected by your app
        options: --health-cmd="curl --fail http://localhost:8529/_api/version || exit 1" --health-interval=20s --health-timeout=10s --health-retries=10

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build WebOCD Service
        run: ./gradlew build
        env:
          ARANGO_HOST: localhost
          ARANGO_PORT: 8529
          ARANGO_USER: root
          ARANGO_PASSWORD: password
          ARANGO_DB: ocdDB

      - name: Print ArangoDB logs
        if: always()  # Ensures this step runs even if the steps before it fail
        run: docker logs $(docker ps -aqf "name=arangodb")
